name: Build LaTeX document

on:
  push:
    tags:
    - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install Pygments
        run: |
          sudo apt-get install python3-pygments
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          args: "-pdf -outdir=Build/ -shell-escape -pdflatex=lualatex main.tex methodology.tex"
      - name: Place the PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            Build/main.pdf
            Build/methodology.pdf
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Build/main.pdf,Build/methodology.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
